baseURL = 'https://statusgrata.ru/'
languageCode = 'ru-ru'
title = 'Status Grata'

[params]
  description = 'Профессиональные IT-решения для вашего бизнеса'

[menu]
  [[menu.main]]
    name = 'Главная'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'О компании'
    url = '/about/'
    weight = 20
  [[menu.main]]
    name = 'Услуги'
    url = '/services/'
    weight = 30
  [[menu.main]]
    name = 'Блог'
    url = '/blog/'
    weight = 40
  [[menu.main]]
    name = 'Контакты'
    url = '/contacts/'
    weight = 50
